import type { PrismaClient } from "@prisma/client";

type SiteCopySeed = {
  key: string;
  namespace: string;
  label: string;
  value: string;
  description?: string;
  multiline?: boolean;
  sortOrder: number;
};

function group(
  namespace: string,
  entries: Array<
    [key: string, label: string, value: string, multiline?: boolean]
  >,
): SiteCopySeed[] {
  return entries.map(([key, label, value, multiline], index) => ({
    key: `${namespace}.${key}`,
    namespace,
    label,
    value,
    multiline: multiline ?? false,
    sortOrder: index * 10,
  }));
}

/** Canonical initial copy only. Runtime rendering never imports this file and
 * therefore cannot use these strings as a fallback when database content is
 * absent. */
export const SITE_COPY_SEED: SiteCopySeed[] = [
  ...group("site", [
    ["name", "Site name", "Watplux"],
    ["title", "Default page title", "Watplux | Reliable solar power solutions"],
    [
      "description",
      "Site description",
      "Solar power equipment, system planning and installation services.",
      true,
    ],
    ["category", "Site category", "Solar energy"],
    ["locale", "Site locale", "en_NG"],
    [
      "keywords",
      "Search keywords",
      "solar power Nigeria\nsolar panels\nsolar inverters\nsolar batteries\nsolar installation\nbackup power",
      true,
    ],
    [
      "openGraphAlt",
      "Social image alternative text",
      "Watplux solar power equipment, planning and installation",
    ],
  ]),
  ...group("chrome", [
    ["skipToMain", "Skip link", "Skip to main content"],
    ["homeAria", "Home link accessibility label", "Watplux home"],
    ["mainNavAria", "Main navigation accessibility label", "Main"],
    ["theme.changeAria", "Theme button label", "Change color theme"],
    ["theme.current", "Current theme template", "Color theme: {theme}"],
    ["theme.light", "Light theme label", "Light"],
    ["theme.dark", "Dark theme label", "Dark"],
    ["theme.system", "System theme label", "System"],
    ["mobile.openAria", "Open mobile menu label", "Open menu"],
    ["mobile.title", "Mobile menu title", "Watplux"],
    ["mobile.subtitle", "Mobile menu subtitle", "Solar shop & services"],
    ["mobile.explore", "Mobile menu section label", "Explore"],
    ["mobile.navAria", "Mobile navigation accessibility label", "Mobile"],
    ["nav.shop.label", "Shop navigation label", "Shop"],
    [
      "nav.shop.description",
      "Shop navigation description",
      "Browse solar equipment and essentials",
    ],
    ["nav.consultation.label", "Consultation navigation label", "Consultation"],
    [
      "nav.consultation.description",
      "Consultation navigation description",
      "Plan the right system for your needs",
    ],
    ["nav.installation.label", "Installation navigation label", "Installation"],
    [
      "nav.installation.description",
      "Installation navigation description",
      "Request professional installation",
    ],
    ["footer.shop.heading", "Footer shop heading", "Shop"],
    ["footer.shop.aria", "Footer shop navigation label", "Shop"],
    ["footer.allProducts", "Footer products link", "All products"],
    ["footer.cart", "Footer cart link", "Cart"],
    ["footer.services.heading", "Footer services heading", "Services"],
    ["footer.services.aria", "Footer services navigation label", "Services"],
    ["footer.consultation", "Footer consultation link", "Solar consultation"],
    ["footer.installation", "Footer installation link", "Installation"],
    ["footer.help.heading", "Footer help heading", "Get help"],
    ["footer.help.aria", "Footer help navigation label", "Get help"],
    ["footer.plan", "Footer planning link", "Plan a system"],
    [
      "footer.requestInstallation",
      "Footer installation request link",
      "Request installation",
    ],
    ["footer.trackRequest", "Footer tracking link", "Track a request"],
    [
      "footer.copyright",
      "Copyright",
      "© {year} {siteName}. All rights reserved.",
    ],
    [
      "footer.tagline",
      "Footer tagline",
      "Reliable energy, designed around real needs.",
    ],
    ["footer.creditPrefix", "Site credit prefix", "Designed and developed by"],
    ["footer.creditName", "Site credit name", "Tetranyble Labs Ltd"],
  ]),
  ...group("home", [
    [
      "hero.badge",
      "Hero badge",
      "Practical solar for real homes and businesses",
    ],
    [
      "hero.title",
      "Hero title",
      "Reliable energy starts with the right system.",
    ],
    [
      "hero.description",
      "Hero description",
      "Shop solar equipment with confidence, or get help choosing and installing a system that fits your actual load and budget.",
      true,
    ],
    ["hero.primaryCta", "Hero primary button", "Shop solar products"],
    ["hero.secondaryCta", "Hero secondary button", "Talk to an expert"],
    ["hero.proof1", "Hero proof point 1", "Transparent product details"],
    ["hero.proof2", "Hero proof point 2", "Secure Paystack checkout"],
    ["hero.proof3", "Hero proof point 3", "Support before and after purchase"],
    ["flow.eyebrow", "Buying flow eyebrow", "A better buying flow"],
    ["flow.title", "Buying flow title", "Product → guidance → installation"],
    ["flow.step1.title", "Buying flow step 1", "Browse equipment"],
    [
      "flow.step1.description",
      "Buying flow step 1 description",
      "Compare useful product and solar-specific specifications.",
    ],
    ["flow.step2.title", "Buying flow step 2", "Get expert guidance"],
    [
      "flow.step2.description",
      "Buying flow step 2 description",
      "Ask for help before you commit to the wrong system size.",
    ],
    ["flow.step3.title", "Buying flow step 3", "Install with confidence"],
    [
      "flow.step3.description",
      "Buying flow step 3 description",
      "Move from purchase to professional installation support.",
    ],
    ["trust.quality", "Trust signal: quality", "Quality-checked equipment"],
    ["trust.delivery", "Trust signal: delivery", "Delivery support"],
    [
      "trust.installation",
      "Trust signal: installation",
      "Professional installation",
    ],
    ["trust.solar", "Trust signal: solar", "Solar-ready components"],
    ["featured.eyebrow", "Featured products eyebrow", "Featured equipment"],
    ["featured.title", "Featured products title", "Built for dependable power"],
    [
      "featured.description",
      "Featured products description",
      "Shop the equipment customers are choosing for homes, businesses, and backup-energy projects.",
      true,
    ],
    ["featured.viewAll", "Featured products link", "View all"],
    ["categories.eyebrow", "Categories eyebrow", "Browse quickly"],
    ["categories.title", "Categories title", "Shop by category"],
    [
      "consultation.eyebrow",
      "Consultation banner eyebrow",
      "Need help choosing?",
    ],
    [
      "consultation.title",
      "Consultation banner title",
      "Size the system before you spend.",
    ],
    [
      "consultation.description",
      "Consultation banner description",
      "Tell us what you need to power and we will help you narrow down the right equipment and capacity.",
      true,
    ],
    ["consultation.cta", "Consultation banner button", "Book a consultation"],
    [
      "installation.eyebrow",
      "Installation banner eyebrow",
      "Already purchased?",
    ],
    [
      "installation.title",
      "Installation banner title",
      "Complete it with professional installation.",
    ],
    [
      "installation.description",
      "Installation banner description",
      "Get installation support for panels, inverters, batteries, and complete solar systems.",
      true,
    ],
    ["installation.cta", "Installation banner button", "Request installation"],
    [
      "social.title",
      "Social image headline",
      "Reliable energy starts with the right system.",
    ],
    [
      "social.description",
      "Social image description",
      "Solar equipment, system planning and professional installation for homes and businesses.",
    ],
  ]),
  ...group("system", [
    ["error.title", "Error page title", "Something went wrong"],
    [
      "error.description",
      "Error page description",
      "An unexpected error occurred. You can try again, or come back later.",
      true,
    ],
    ["error.retry", "Error retry button", "Try again"],
  ]),
  ...group("services", [
    ["consultation.metaTitle", "Consultation page title", "Solar consultation"],
    [
      "consultation.metaDescription",
      "Consultation metadata description",
      "Request a solar consultation and give our team the information needed to size a practical system for your property.",
      true,
    ],
    ["consultation.badge", "Consultation badge", "Solar advisory"],
    [
      "consultation.title",
      "Consultation heading",
      "Plan the right solar system before you spend.",
    ],
    [
      "consultation.description",
      "Consultation introduction",
      "Share your loads, backup expectations and site details. Our team will review the request and contact you with the next practical step.",
      true,
    ],
    ["consultation.step1.title", "Consultation step 1", "Understand the site"],
    [
      "consultation.step1.description",
      "Consultation step 1 description",
      "Tell us where and how you use power.",
    ],
    ["consultation.step2.title", "Consultation step 2", "Size the system"],
    [
      "consultation.step2.description",
      "Consultation step 2 description",
      "We translate your needs into realistic capacity.",
    ],
    ["consultation.step3.title", "Consultation step 3", "Plan for backup"],
    [
      "consultation.step3.description",
      "Consultation step 3 description",
      "We align batteries and inverter capacity to your goals.",
    ],
    [
      "consultation.loading",
      "Consultation form loading text",
      "Loading consultation form…",
    ],
    ["installation.metaTitle", "Installation page title", "Solar installation"],
    [
      "installation.metaDescription",
      "Installation metadata description",
      "Request professional solar installation, assessment and commissioning from Watplux.",
      true,
    ],
    ["installation.badge", "Installation badge", "Installation service"],
    [
      "installation.title",
      "Installation heading",
      "Professional installation, from site check to commissioning.",
    ],
    [
      "installation.description",
      "Installation introduction",
      "Whether you bought the equipment from Watplux or already own it, submit the site details so the team can evaluate the work before scheduling.",
      true,
    ],
    ["installation.step1.title", "Installation step 1", "Assess"],
    [
      "installation.step1.description",
      "Installation step 1 description",
      "Review equipment, site constraints and installation readiness.",
    ],
    ["installation.step2.title", "Installation step 2", "Install"],
    [
      "installation.step2.description",
      "Installation step 2 description",
      "Plan a safe installation with clear responsibility and scope.",
    ],
    ["installation.step3.title", "Installation step 3", "Commission"],
    [
      "installation.step3.description",
      "Installation step 3 description",
      "Test the finished system before handover.",
    ],
    [
      "installation.loading",
      "Installation form loading text",
      "Loading installation form…",
    ],
    ["form.nameRequired", "Missing name validation", "Full name is required."],
    ["form.emailRequired", "Missing email validation", "Email is required."],
    ["form.phoneRequired", "Missing phone validation", "Phone is required."],
    ["form.submitErrorTitle", "Submit error title", "Could not submit request"],
    ["form.contactTitle", "Contact section title", "Your contact details"],
    [
      "form.contactDescription",
      "Contact section description",
      "We use these details to follow up on this request.",
    ],
    ["form.fullName", "Full name label", "Full name"],
    ["form.email", "Email label", "Email"],
    ["form.phone", "Phone label", "Phone"],
    ["form.needsTitle", "Needs section title", "Property and power needs"],
    [
      "form.needsDescription",
      "Needs section description",
      "Give us enough context to prepare before we contact you.",
    ],
    ["form.propertyType", "Property type label", "Property type"],
    ["form.residential", "Residential option", "Residential"],
    ["form.commercial", "Commercial option", "Commercial"],
    ["form.industrial", "Industrial option", "Industrial"],
    ["form.location", "Location label", "Location"],
    [
      "form.locationPlaceholder",
      "Location placeholder",
      "Area, city or full address",
    ],
    ["form.electricity", "Electricity label", "Current electricity situation"],
    ["form.usage", "Usage label", "Estimated monthly usage (kWh)"],
    ["form.backup", "Backup label", "Desired backup time (hours)"],
    ["form.appliances", "Appliances label", "Appliances / loads"],
    [
      "form.appliancesHelp",
      "Appliances help",
      "List the major equipment you want powered.",
    ],
    ["form.equipment", "Existing equipment label", "Existing solar equipment"],
    ["form.budget", "Budget label", "Budget range"],
    ["form.optional", "Optional placeholder", "Optional"],
    ["form.appointment", "Appointment label", "Preferred appointment"],
    [
      "form.additional",
      "Additional information label",
      "Anything else we should know?",
    ],
    ["form.submitting", "Submitting label", "Submitting…"],
    [
      "form.installationSubmit",
      "Installation submit button",
      "Request installation",
    ],
    [
      "form.consultationSubmit",
      "Consultation submit button",
      "Request consultation",
    ],
    ["form.invalid", "Invalid request fallback", "Check the request details."],
    [
      "form.failed",
      "Request failure fallback",
      "We could not submit your request. Please try again.",
    ],
    ["submitted.metaTitle", "Submitted page title", "Request received"],
    ["submitted.title", "Submitted heading", "Request received"],
    [
      "submitted.description",
      "Submitted description",
      "Our team can now review the information you submitted and follow up with the next step.",
      true,
    ],
    [
      "submitted.reference",
      "Request reference template",
      "Your request reference is #{id}.",
    ],
    ["submitted.products", "Browse products button", "Browse products"],
    ["submitted.requests", "View requests button", "View my requests"],
  ]),
  ...group("catalog", [
    ["metaTitle", "Catalog page title", "Shop"],
    [
      "metaDescription",
      "Catalog metadata description",
      "Browse solar panels, inverters, batteries, and accessories.",
    ],
    ["title", "Catalog heading", "Shop dependable power solutions"],
    [
      "description",
      "Catalog introduction",
      "Compare panels, inverters, batteries and accessories selected for homes, businesses and backup-energy projects.",
      true,
    ],
    [
      "productsShown",
      "Products shown template",
      "{count}{plus} products shown",
    ],
    ["resultsAria", "Product results accessibility label", "Product results"],
    ["clearAll", "Clear all filters button", "Clear all filters"],
    ["empty.filteredTitle", "Filtered empty title", "No matching products"],
    [
      "empty.catalogTitle",
      "Empty catalog title",
      "Our catalog is being prepared",
    ],
    [
      "empty.filteredDescription",
      "Filtered empty description",
      "No products match the selected filters. Adjust or clear them to explore more equipment.",
      true,
    ],
    [
      "empty.catalogDescription",
      "Empty catalog description",
      "We’re preparing products for online purchase. Our team can still help you choose the right equipment for your project.",
      true,
    ],
    ["empty.clear", "Empty state clear button", "Clear filters"],
    ["empty.advice", "Empty state advice button", "Get product advice"],
    ["viewMore", "View more products button", "View more products"],
    ["card.noImage", "Product card missing image", "No image yet"],
    ["card.featured", "Featured badge", "Featured"],
    ["grid.emptyTitle", "Default empty grid title", "No products found"],
    [
      "grid.emptyDescription",
      "Default empty grid description",
      "Products will appear here when they become available.",
    ],
    [
      "purchase.unavailable",
      "Unavailable product message",
      "This product is unavailable.",
    ],
    [
      "purchase.addFailed",
      "Add-to-cart failure",
      "Could not add this item to your cart.",
    ],
    ["purchase.added", "Added-to-cart success", "Added to cart."],
    [
      "purchase.generalError",
      "Cart error fallback",
      "Something went wrong. Please try again.",
    ],
    ["purchase.variantAria", "Variant selector label", "Select variant"],
    [
      "purchase.currentlyUnavailable",
      "Unavailable stock state",
      "Currently unavailable.",
    ],
    ["purchase.inStock", "In-stock state", "In stock"],
    ["purchase.outOfStock", "Out-of-stock state", "Out of stock"],
    ["purchase.quantity", "Quantity label", "Quantity"],
    ["purchase.decrease", "Decrease quantity label", "Decrease quantity"],
    ["purchase.increase", "Increase quantity label", "Increase quantity"],
    ["purchase.adding", "Adding-to-cart label", "Adding…"],
    ["purchase.add", "Add-to-cart button", "Add to cart"],
    ["gallery.noImage", "Gallery missing image", "No image available"],
    ["gallery.aria", "Product gallery label", "Product images"],
    [
      "gallery.viewImage",
      "Gallery thumbnail template",
      "View image {index} of {count}",
    ],
    ["detail.home", "Product breadcrumb home", "Home"],
    ["detail.help", "Product help heading", "Need help choosing?"],
    ["detail.consultation", "Product consultation link", "Book a consultation"],
    [
      "detail.installation",
      "Product installation link",
      "Request installation",
    ],
    ["detail.description", "Product description heading", "Description"],
    ["detail.related", "Related products heading", "Related products"],
    [
      "specs.technical",
      "Technical specifications heading",
      "Technical specifications",
    ],
    ["specs.other", "Other specifications heading", "Other specifications"],
    ["specs.powerRating", "Power rating label", "Power rating"],
    ["specs.voltage", "Voltage label", "Voltage"],
    ["specs.capacity", "Capacity label", "Capacity"],
    ["specs.current", "Rated current label", "Rated current"],
    ["specs.phase", "Phase label", "Phase"],
    ["specs.efficiency", "Efficiency label", "Efficiency"],
    ["specs.mpptMin", "MPPT minimum label", "MPPT min voltage"],
    ["specs.mpptMax", "MPPT maximum label", "MPPT max voltage"],
    ["specs.weight", "Weight label", "Weight"],
    ["specs.length", "Length label", "Length"],
    ["specs.width", "Width label", "Width"],
    ["specs.height", "Height label", "Height"],
    ["brand.metaTitle", "Brand title template", "{brand} products"],
    [
      "brand.metaDescription",
      "Brand description template",
      "Shop {brand} solar equipment.",
    ],
    ["brand.eyebrow", "Brand page eyebrow", "Product brand"],
    [
      "brand.emptyTitle",
      "Brand empty title template",
      "No {brand} products yet",
    ],
    [
      "brand.emptyDescription",
      "Brand empty description",
      "This brand has no available products right now. Explore the full catalog or ask our team for a suitable alternative.",
      true,
    ],
    ["category.eyebrow", "Category page eyebrow", "Product category"],
    [
      "category.emptyTitle",
      "Category empty title template",
      "No {category} products yet",
    ],
    [
      "category.emptyDescription",
      "Category empty description",
      "We’re still preparing this collection. Browse the full catalog or speak with our team for help finding the right equipment.",
      true,
    ],
    ["collection.alternative", "Alternative button", "Find an alternative"],
    ["collection.advice", "Product advice button", "Get product advice"],
    [
      "collection.allProducts",
      "Browse all products button",
      "Browse all products",
    ],
    ["notFound.productTitle", "Missing product title", "Product not found"],
    [
      "notFound.productDescription",
      "Missing product description",
      "This product doesn’t exist or is no longer available.",
    ],
    ["notFound.brandTitle", "Missing brand title", "Brand not found"],
    [
      "notFound.brandDescription",
      "Missing brand description",
      "This brand doesn’t exist or is no longer available.",
    ],
    ["notFound.categoryTitle", "Missing category title", "Category not found"],
    [
      "notFound.categoryDescription",
      "Missing category description",
      "This category doesn’t exist or is no longer available.",
    ],
    [
      "filters.wholeNumber",
      "Whole-number validation",
      "Enter a whole number of zero or more.",
    ],
    [
      "filters.maxPrice",
      "Maximum price validation",
      "Maximum price must be at least the minimum price.",
    ],
    [
      "filters.maxPower",
      "Maximum power validation",
      "Maximum power must be at least the minimum power.",
    ],
    ["filters.title", "Filters title", "Filters"],
    [
      "filters.description",
      "Filters description",
      "Refine the equipment shown.",
    ],
    ["filters.search", "Search label", "Search"],
    [
      "filters.searchPlaceholder",
      "Search placeholder",
      "Panels, inverters, batteries…",
    ],
    ["filters.category", "Category filter label", "Category"],
    ["filters.allCategories", "All categories label", "All categories"],
    ["filters.brand", "Brand filter label", "Brand"],
    ["filters.allBrands", "All brands label", "All brands"],
    ["filters.priceRange", "Price range label", "Price range (₦)"],
    ["filters.powerRange", "Power range label", "Power range (W)"],
    ["filters.minimum", "Minimum label", "Minimum"],
    ["filters.maximum", "Maximum label", "Maximum"],
    ["filters.voltage", "Voltage filter label", "Voltage (V)"],
    ["filters.phase", "Phase filter label", "Phase"],
    ["filters.singlePhase", "Single-phase option", "Single-phase"],
    ["filters.threePhase", "Three-phase option", "Three-phase"],
    ["filters.anyPhase", "Any phase option", "Any phase"],
    ["filters.stock", "In-stock filter label", "In-stock products only"],
    ["filters.sort", "Sort label", "Sort by"],
    ["filters.newest", "Newest sort option", "Newest"],
    ["filters.featured", "Featured sort option", "Featured first"],
    ["filters.priceAsc", "Ascending price option", "Price: low to high"],
    ["filters.priceDesc", "Descending price option", "Price: high to low"],
    ["filters.apply", "Apply filters button", "Apply filters"],
    ["filters.clear", "Clear filters button", "Clear filters"],
    ["filters.filterAria", "Filter trigger label", "Filter products"],
    ["filters.drawerTitle", "Filter drawer title", "Filter products"],
    [
      "filters.drawerDescription",
      "Filter drawer description",
      "Narrow the catalog by equipment details and availability.",
    ],
  ]),
  ...group("commerce", [
    ["cart.metaTitle", "Cart page title", "Your cart"],
    ["cart.title", "Cart heading", "Your cart"],
    ["cart.viewAria", "View cart label", "View cart"],
    ["cart.review", "Cart drawer description", "Review items before checkout"],
    [
      "cart.itemsReady",
      "Cart items ready template",
      "{count} {itemLabel} ready to review",
    ],
    ["cart.itemSingular", "Singular item", "item"],
    ["cart.itemPlural", "Plural items", "items"],
    ["cart.loading", "Loading cart label", "Loading cart"],
    ["cart.loadFailed", "Cart load error", "Could not load your cart."],
    [
      "cart.loadFailedTitle",
      "Cart load error title",
      "Couldn’t load your cart",
    ],
    ["cart.retry", "Cart retry button", "Try again"],
    ["cart.emptyTitle", "Empty cart title", "Your cart is empty"],
    [
      "cart.emptyPageDescription",
      "Empty cart page description",
      "Browse our catalog to find dependable solar equipment for your home or business.",
    ],
    [
      "cart.emptyDrawerDescription",
      "Empty cart drawer description",
      "Add products to review them here before checkout.",
    ],
    ["cart.browse", "Browse products button", "Browse products"],
    ["cart.viewFull", "View full cart button", "View full cart"],
    ["cart.updateFailed", "Cart update failure", "Could not update this item."],
    ["cart.removeFailed", "Cart remove failure", "Could not remove this item."],
    ["cart.unavailable", "Unavailable cart item", "No longer available"],
    ["cart.decrease", "Decrease quantity label", "Decrease quantity"],
    ["cart.increase", "Increase quantity label", "Increase quantity"],
    ["cart.remove", "Remove item template", "Remove {product} from cart"],
    ["summary.title", "Order summary heading", "Order summary"],
    [
      "summary.items",
      "Summary item template",
      "{count} {itemLabel} in this order",
    ],
    ["summary.subtotal", "Subtotal label", "Subtotal"],
    [
      "summary.note",
      "Order summary note",
      "Your final order total is confirmed before you continue to secure payment.",
      true,
    ],
    ["summary.checkout", "Checkout button", "Proceed to checkout"],
    ["checkout.metaTitle", "Checkout page title", "Checkout"],
    ["checkout.eyebrow", "Checkout eyebrow", "Secure checkout"],
    ["checkout.title", "Checkout heading", "Complete your order"],
    [
      "checkout.description",
      "Checkout introduction",
      "Confirm where your items should go, then continue to Paystack to pay.",
    ],
    [
      "checkout.invalidEmail",
      "Checkout email validation",
      "Enter a valid email address.",
    ],
    [
      "checkout.emailRequired",
      "Guest email validation",
      "Email is required for guest checkout.",
    ],
    [
      "checkout.continueError",
      "Continue error title",
      "Could not continue to payment",
    ],
    [
      "checkout.checkDetails",
      "Checkout details error",
      "Please check your details and try again.",
    ],
    ["checkout.failed", "Checkout failure title", "Checkout failed"],
    [
      "checkout.generalError",
      "Checkout general error",
      "Something went wrong. Please try again.",
    ],
    ["checkout.contact", "Checkout contact heading", "Contact"],
    [
      "checkout.contactDescription",
      "Checkout contact description",
      "We use these details for your order and payment confirmation.",
    ],
    ["checkout.email", "Checkout email label", "Email"],
    ["checkout.phone", "Checkout phone label", "Phone"],
    [
      "checkout.phoneHelp",
      "Checkout phone help",
      "Optional, but useful for delivery updates.",
    ],
    ["checkout.delivery", "Delivery heading", "Delivery details"],
    [
      "checkout.deliveryDescription",
      "Delivery description",
      "Enter the address where this order should be delivered.",
    ],
    ["checkout.fullName", "Delivery full name label", "Full name"],
    ["checkout.address", "Address label", "Address"],
    ["checkout.address2", "Address line 2 label", "Address line 2"],
    ["checkout.city", "City label", "City"],
    ["checkout.state", "State label", "State"],
    ["checkout.postal", "Postal code label", "Postal code"],
    ["checkout.notes", "Delivery notes label", "Delivery notes"],
    [
      "checkout.preparing",
      "Preparing payment label",
      "Preparing secure payment…",
    ],
    [
      "checkout.continue",
      "Continue payment button",
      "Continue to secure payment",
    ],
    [
      "checkout.security",
      "Payment security note",
      "Payment is processed securely through Paystack. Watplux never receives your card details.",
      true,
    ],
    ["payment.metaTitle", "Payment result page title", "Payment status"],
    [
      "payment.checkFailed",
      "Payment check failure",
      "Could not check payment status.",
    ],
    [
      "payment.retryFailed",
      "Payment retry failure",
      "Could not retry payment.",
    ],
    [
      "payment.startFailed",
      "Payment start failure",
      "Could not start a new payment attempt.",
    ],
    ["payment.successTitle", "Payment success title", "Payment successful"],
    [
      "payment.successDescription",
      "Payment success description",
      "Thank you — your order is confirmed.",
    ],
    [
      "payment.reference",
      "Guest order reference template",
      "Order #{id} — save this reference for your records.",
    ],
    ["payment.viewOrder", "View order button", "View your order"],
    ["payment.failedTitle", "Payment failure title", "Payment unsuccessful"],
    [
      "payment.failedDescription",
      "Payment failure description",
      "Your payment could not be completed.",
    ],
    ["payment.starting", "Starting payment label", "Starting…"],
    ["payment.retry", "Retry payment button", "Try payment again"],
    [
      "payment.checkTitle",
      "Payment check error title",
      "Couldn’t check payment status",
    ],
    ["payment.checkAgain", "Check payment button", "Check again"],
    [
      "payment.slowTitle",
      "Slow confirmation title",
      "Still confirming your payment",
    ],
    [
      "payment.confirmingTitle",
      "Payment confirming title",
      "Confirming your payment…",
    ],
    [
      "payment.slowDescription",
      "Slow confirmation description",
      "This is taking longer than expected. You can check again, or come back later — we'll email you once it's confirmed.",
      true,
    ],
    [
      "payment.confirmingDescription",
      "Payment confirming description",
      "We're checking with Paystack. This usually takes a few seconds.",
    ],
    [
      "order.cancelFailed",
      "Order cancellation failure",
      "Could not cancel this order.",
    ],
    ["order.cancelled", "Order cancelled success", "Order cancelled."],
    ["order.retryFailed", "Order retry failure", "Could not retry payment."],
    ["order.retry", "Retry payment button", "Retry payment"],
    [
      "order.confirmCancel",
      "Confirm cancellation button",
      "Confirm cancellation",
    ],
    ["order.neverMind", "Cancel dismissal button", "Never mind"],
    ["order.cancel", "Cancel order button", "Cancel order"],
    ["status.pending", "Pending payment status", "Pending payment"],
    ["status.paid", "Paid status", "Paid"],
    ["status.processing", "Processing status", "Processing"],
    ["status.dispatch", "Ready for dispatch status", "Ready for dispatch"],
    ["status.shipped", "Shipped status", "Shipped"],
    ["status.delivered", "Delivered status", "Delivered"],
    ["status.cancelled", "Cancelled status", "Cancelled"],
    ["status.refunded", "Refunded status", "Refunded"],
  ]),
  ...group("auth", [
    ["emailPlaceholder", "Email placeholder", "you@example.com"],
    ["emailLabel", "Email label", "Email address"],
    ["passwordLabel", "Password label", "Password"],
    [
      "passwordHelp",
      "Password guidance",
      "Use at least 10 characters and a strong mix of characters.",
    ],
    ["backToSignIn", "Back to sign in button", "Back to sign in"],
    ["login.metaTitle", "Sign-in page title", "Sign in"],
    ["login.brand", "Sign-in brand eyebrow", "Watplux Solar"],
    [
      "login.pitch",
      "Sign-in pitch",
      "One account for products, payments and your solar orders.",
    ],
    ["login.cartTitle", "Persistent cart title", "Persistent cart."],
    [
      "login.cartDescription",
      "Persistent cart description",
      "Pick up where you left off on any device.",
    ],
    ["login.ordersTitle", "Order visibility title", "Order visibility."],
    [
      "login.ordersDescription",
      "Order visibility description",
      "Track every order and retry a pending payment safely.",
    ],
    ["login.securityTitle", "Secure access title", "Secure access."],
    [
      "login.securityDescription",
      "Secure access description",
      "Authentication and sessions are handled by Better Auth.",
    ],
    ["login.welcome", "Welcome label", "Welcome back"],
    ["login.title", "Sign-in heading", "Sign in"],
    [
      "login.description",
      "Sign-in description",
      "Manage your cart, orders and payments.",
    ],
    ["login.verifiedTitle", "Email verified title", "Email verified"],
    ["login.resetTitle", "Password updated title", "Password updated"],
    [
      "login.verifiedDescription",
      "Email verified description",
      "Your account is ready. You can sign in now.",
    ],
    [
      "login.resetDescription",
      "Password updated description",
      "Your new password is active. Sign in to continue.",
    ],
    ["login.errorTitle", "Sign-in error title", "Could not sign in"],
    ["login.forgot", "Forgot password link", "Forgot password?"],
    ["login.signingIn", "Signing-in label", "Signing in…"],
    ["login.submit", "Sign-in button", "Sign in"],
    ["login.new", "Registration prompt", "New to Watplux?"],
    ["login.create", "Create account link", "Create an account"],
    [
      "login.invalid",
      "Invalid login fallback",
      "Enter a valid email and password.",
    ],
    [
      "login.verify",
      "Unverified email error",
      "Verify your email before signing in. We sent a fresh verification link.",
    ],
    [
      "login.credentials",
      "Invalid credentials error",
      "Invalid email or password.",
    ],
    ["register.metaTitle", "Registration page title", "Create account"],
    ["register.eyebrow", "Registration eyebrow", "Customer account"],
    ["register.title", "Registration heading", "Create your account"],
    [
      "register.description",
      "Registration description",
      "Save your cart, track orders and manage payments from one place.",
    ],
    [
      "register.errorTitle",
      "Registration error title",
      "Could not create account",
    ],
    ["register.name", "Registration name label", "Full name"],
    ["register.creating", "Creating account label", "Creating account…"],
    ["register.submit", "Registration button", "Create account"],
    [
      "register.existing",
      "Existing account prompt",
      "Already have an account?",
    ],
    ["register.signIn", "Registration sign-in link", "Sign in"],
    [
      "register.invalid",
      "Invalid registration fallback",
      "Check your details and try again.",
    ],
    [
      "register.failed",
      "Registration failure fallback",
      "We could not create that account. Try signing in if you already registered.",
    ],
    ["forgot.metaTitle", "Forgot-password page title", "Forgot password"],
    ["forgot.title", "Forgot-password heading", "Reset your password"],
    [
      "forgot.description",
      "Forgot-password description",
      "Enter your account email and we’ll send a secure reset link if the address is registered.",
      true,
    ],
    [
      "forgot.errorTitle",
      "Reset request error title",
      "Could not request a reset",
    ],
    ["forgot.successTitle", "Reset request success title", "Check your inbox"],
    [
      "forgot.successDescription",
      "Reset request success description",
      "If an account uses that address, we sent a password-reset link.",
    ],
    ["forgot.sending", "Sending reset label", "Sending link…"],
    ["forgot.submit", "Send reset button", "Send reset link"],
    [
      "forgot.invalid",
      "Reset email validation fallback",
      "Enter a valid email address.",
    ],
    ["reset.metaTitle", "Reset page title", "Choose a new password"],
    ["reset.invalidTitle", "Invalid reset heading", "Reset link unavailable"],
    ["reset.title", "Reset heading", "Choose a new password"],
    [
      "reset.invalidDescription",
      "Invalid reset description",
      "This password-reset link is invalid or has expired. Request a new link to continue.",
      true,
    ],
    ["reset.requestAgain", "Request reset link button", "Request another link"],
    [
      "reset.description",
      "Reset description",
      "Your new password will replace the old one and sign out existing sessions for your protection.",
      true,
    ],
    ["reset.errorTitle", "Reset error title", "Could not reset password"],
    ["reset.newPassword", "New password label", "New password"],
    ["reset.confirmPassword", "Confirm password label", "Confirm new password"],
    ["reset.updating", "Updating password label", "Updating password…"],
    ["reset.submit", "Update password button", "Update password"],
    [
      "reset.invalid",
      "Invalid reset fields fallback",
      "Check the password fields and try again.",
    ],
    [
      "reset.expired",
      "Expired reset error",
      "This reset link is invalid or has expired. Request a new link and try again.",
    ],
    ["verify.metaTitle", "Verify-email page title", "Verify your email"],
    ["verify.title", "Verify-email heading", "Check your email"],
    [
      "verify.sentDescription",
      "New account verification description",
      "Your account was created. Use the verification link we sent before signing in.",
      true,
    ],
    [
      "verify.description",
      "Verification description",
      "Use the verification link in your inbox to activate your account.",
    ],
    ["verify.fresh", "Fresh verification prompt", "Need a fresh link?"],
    [
      "verify.errorTitle",
      "Verification resend error",
      "Could not resend verification",
    ],
    [
      "verify.successTitle",
      "Verification resend success",
      "Verification link requested",
    ],
    [
      "verify.successDescription",
      "Verification resend description",
      "If that address is awaiting verification, a fresh link is on its way.",
    ],
    ["verify.sending", "Verification sending label", "Sending…"],
    [
      "verify.submit",
      "Verification resend button",
      "Resend verification email",
    ],
    [
      "verify.invalid",
      "Verification email validation fallback",
      "Enter a valid email address.",
    ],
  ]),
  ...group("account", [
    ["userFallback", "Unnamed user fallback", "User"],
    ["nav.title", "Signed-out account title", "Your Watplux account"],
    [
      "nav.description",
      "Signed-out account description",
      "Sign in to track orders and service requests.",
    ],
    ["nav.create", "Create account button", "Create account"],
    ["nav.login", "Log-in button", "Log in"],
    ["nav.admin", "Admin dashboard link", "Admin dashboard"],
    ["nav.settings", "Account settings link", "Account settings"],
    ["nav.orders", "My orders link", "My orders"],
    ["nav.services", "Service requests link", "Service requests"],
    ["nav.signOut", "Sign-out button", "Sign out"],
    ["nav.account", "Account link", "Account"],
    ["nav.ordersShort", "Orders link", "Orders"],
    ["nav.menuAria", "Account menu template", "Account menu for {email}"],
    ["eyebrow", "Account eyebrow", "Your account"],
    ["welcome", "Account welcome template", "Welcome back, {name}"],
    [
      "description",
      "Account introduction",
      "Track purchases, continue shopping, and manage the sessions connected to your account.",
      true,
    ],
    ["browse", "Browse products button", "Browse products"],
    ["details.title", "Account details heading", "Account details"],
    [
      "details.description",
      "Account details description",
      "Your identity is managed securely through Better Auth.",
    ],
    ["details.name", "Name label", "Name"],
    ["details.email", "Email label", "Email"],
    ["orders.title", "Orders card title", "Your orders"],
    [
      "orders.description",
      "Orders card description",
      "Review orders, payment attempts and delivery details.",
    ],
    ["orders.view", "View orders button", "View orders"],
    ["services.title", "Services card title", "Service requests"],
    [
      "services.description",
      "Services card description",
      "Track solar consultations and installation requests.",
    ],
    ["services.view", "View requests button", "View requests"],
    ["cart.title", "Cart card title", "Shopping cart"],
    [
      "cart.description",
      "Cart card description",
      "Return to the cart you are building and continue to checkout.",
    ],
    ["cart.open", "Open cart button", "Open cart"],
    ["password.title", "Password card title", "Password"],
    [
      "password.description",
      "Password card description",
      "Changing it also revokes your other active sessions.",
    ],
    ["sessions.title", "Sessions title", "Sessions"],
    [
      "sessions.description",
      "Sessions description",
      "End this session or revoke every active session for your account.",
    ],
    ["sessions.logout", "Log-out button", "Log out"],
    [
      "sessions.logoutAll",
      "Log out all devices button",
      "Log out of all devices",
    ],
    [
      "sessions.help",
      "Sessions help",
      "Use “log out of all devices” if you no longer recognise a signed-in device.",
      true,
    ],
    [
      "password.errorTitle",
      "Password update error title",
      "Could not update password",
    ],
    [
      "password.successTitle",
      "Password update success title",
      "Password updated",
    ],
    ["password.current", "Current password label", "Current password"],
    ["password.new", "New password label", "New password"],
    [
      "password.help",
      "New password help",
      "Your new password is checked as you type.",
    ],
    ["password.confirm", "Confirm password label", "Confirm new password"],
    ["password.updating", "Updating password label", "Updating…"],
    ["password.submit", "Update password button", "Update password"],
    [
      "password.invalid",
      "Password validation fallback",
      "Check the password fields.",
    ],
    [
      "password.success",
      "Password updated message",
      "Password updated. Other signed-in devices were logged out.",
    ],
    [
      "password.failed",
      "Password update failure",
      "We could not change your password. Check your current password and try again.",
    ],
    ["avatar.title", "Profile photo heading", "Profile photo"],
    [
      "avatar.description",
      "Profile photo description",
      "Upload a JPEG, PNG, WebP, or AVIF image. It will be cropped to a square and optimized automatically.",
      true,
    ],
    [
      "avatar.updateFailed",
      "Photo update failure",
      "Could not update your photo.",
    ],
    ["avatar.updated", "Photo updated message", "Profile photo updated"],
    ["avatar.uploadFailed", "Photo upload error title", "Upload failed"],
    ["avatar.tryAgain", "Generic retry message", "Please try again."],
    [
      "avatar.removeFailed",
      "Photo removal failure",
      "Could not remove your photo.",
    ],
    ["avatar.removed", "Photo removed message", "Profile photo removed"],
    [
      "avatar.removeError",
      "Photo removal error title",
      "Could not remove photo",
    ],
    ["avatar.uploading", "Photo uploading label", "Uploading…"],
    ["avatar.change", "Change photo button", "Change photo"],
    ["avatar.upload", "Upload photo button", "Upload photo"],
    ["avatar.remove", "Remove photo button", "Remove"],
    [
      "avatar.confirmTitle",
      "Remove photo confirmation title",
      "Remove profile photo?",
    ],
    [
      "avatar.confirmDescription",
      "Remove photo confirmation description",
      "Your initials will be shown until you upload another photo.",
    ],
    ["avatar.confirm", "Remove photo confirmation button", "Remove photo"],
    ["orders.metaTitle", "Orders page title", "Your orders"],
    ["orders.emptyTitle", "No orders title", "You haven’t placed an order yet"],
    [
      "orders.emptyDescription",
      "No orders description",
      "Your purchases and delivery progress will appear here after checkout.",
    ],
    ["orders.heading", "Orders heading", "Your orders"],
    ["orders.column.order", "Order column", "Order"],
    ["orders.column.date", "Date column", "Date"],
    ["orders.column.status", "Status column", "Status"],
    ["orders.column.total", "Total column", "Total"],
    ["order.metaTitle", "Order detail page title", "Order detail"],
    ["order.heading", "Order heading template", "Order {number}"],
    ["order.placed", "Order placed template", "Placed {date}"],
    ["order.subtotal", "Order subtotal label", "Subtotal"],
    ["order.delivery", "Order delivery label", "Delivery"],
    ["order.tax", "Order tax label", "Tax"],
    ["order.total", "Order total label", "Total"],
    ["order.shipping", "Shipping address heading", "Shipping address"],
    ["order.history", "Status history heading", "Status history"],
    ["order.notFoundTitle", "Missing order title", "Order not found"],
    [
      "order.notFoundDescription",
      "Missing order description",
      "This order doesn’t exist or isn’t associated with your account.",
    ],
    ["order.viewAll", "View orders button", "View your orders"],
    ["requests.eyebrow", "Requests eyebrow", "Service requests"],
    ["requests.title", "Requests heading", "Consultation & installation"],
    [
      "requests.description",
      "Requests introduction",
      "Track requests submitted while signed in.",
    ],
    ["requests.consultation", "New consultation button", "New consultation"],
    [
      "requests.installation",
      "Request installation button",
      "Request installation",
    ],
    ["requests.emptyTitle", "No requests title", "No service requests yet"],
    [
      "requests.emptyDescription",
      "No requests description",
      "Tell us what you need and track every update here from submission through completion.",
    ],
    ["request.all", "All requests link", "← All requests"],
    ["request.reference", "Request reference template", "Request #{id}"],
    ["request.details", "Request details heading", "Request details"],
    ["request.property", "Property label", "Property"],
    ["request.location", "Location label", "Location"],
    ["request.backup", "Desired backup label", "Desired backup"],
    ["request.hours", "Hours template", "{hours} hours"],
    ["request.budget", "Budget label", "Budget"],
    ["request.electricity", "Electricity label", "Current electricity"],
    ["request.appliances", "Appliances label", "Appliances"],
    ["request.equipment", "Existing equipment label", "Existing equipment"],
    [
      "request.additional",
      "Additional information label",
      "Additional information",
    ],
  ]),
  ...group("email", [
    [
      "automated",
      "Automated email footer",
      "This is an automated transactional message from {siteName}.",
    ],
    [
      "buttonFallback",
      "Email button fallback",
      "If the button does not work, copy and paste this address into your browser:",
    ],
    ["hello", "Generic greeting", "Hello,"],
    ["greeting", "Named greeting template", "Hi {name},"],
    [
      "verify.subject",
      "Verification email subject",
      "Verify your {siteName} email",
    ],
    [
      "verify.text",
      "Verification email plain text",
      "{greeting}\n\nVerify your email address to finish setting up your {siteName} account:\n{url}\n\n{expiry}",
      true,
    ],
    ["verify.title", "Verification email title", "Verify your email address"],
    [
      "verify.description",
      "Verification email description",
      "Finish setting up your account and protect access to your orders and service requests.",
    ],
    ["verify.action", "Verification email button", "Verify email"],
    [
      "verify.expiry",
      "Verification email expiry note",
      "This link expires in one hour. If you did not create this account, you can ignore this email.",
    ],
    [
      "reset.subject",
      "Password reset email subject",
      "Reset your {siteName} password",
    ],
    [
      "reset.text",
      "Password reset plain text",
      "{greeting}\n\nUse this secure link to reset your {siteName} password:\n{url}\n\n{expiry}",
      true,
    ],
    ["reset.title", "Password reset email title", "Reset your password"],
    [
      "reset.description",
      "Password reset email description",
      "Use the secure link below to choose a new password for your account.",
    ],
    ["reset.action", "Password reset email button", "Reset password"],
    [
      "reset.expiry",
      "Password reset expiry note",
      "This link expires in one hour. If you did not request a password reset, you can ignore this email.",
    ],
    ["service.there", "Service email unnamed recipient", "there"],
    [
      "service.subject",
      "Service request email subject",
      "{serviceLabel} request received — #{reference}",
    ],
    [
      "service.text",
      "Service request plain text",
      "Hi {name},\n\nWe received your {serviceLabel} request. Your reference is #{reference}. Our team will review it and contact you with the next step.\n\nTrack your requests: {trackingUrl}",
      true,
    ],
    [
      "service.title",
      "Service request email title",
      "Your request is safely with us.",
    ],
    [
      "service.description",
      "Service request email description",
      "We received your {serviceLabel} request. Our team will review the details and contact you with the next practical step.",
    ],
    [
      "service.reference",
      "Service request reference label",
      "Request reference",
    ],
    ["service.action", "Track requests email button", "Track service requests"],
    [
      "service.consultation",
      "Consultation service label",
      "Solar consultation",
    ],
    ["service.sizing", "System sizing service label", "System sizing"],
    [
      "service.installation",
      "Installation service label",
      "Solar installation",
    ],
    ["service.maintenance", "Maintenance service label", "Solar maintenance"],
    ["service.assessment", "Site assessment service label", "Site assessment"],
    [
      "service.sms",
      "Service acknowledgement SMS",
      "{siteName}: We received your {serviceLabel} request #{reference}. Our team will review it and contact you with the next step.",
      true,
    ],
  ]),
];

export async function seedSiteCopy(db: PrismaClient): Promise<void> {
  for (const entry of SITE_COPY_SEED) {
    await db.siteCopy.upsert({
      where: { key: entry.key },
      create: entry,
      update: {
        namespace: entry.namespace,
        label: entry.label,
        description: entry.description,
        multiline: entry.multiline,
        sortOrder: entry.sortOrder,
      },
    });
  }
}
